# Use this file to configure Fiji's primary Python environment.
# See fiji.py for the Python-based Fiji startup script.

name: fiji
channels:
  - conda-forge
dependencies:
  - python = 3.12
  - pip
  - pip:
    # PyImageJ is used for in-process Java<->Python integration.
    # https://py.imagej.net/
    - pyimagej>=1.7.0

    # Appose facilitates interprocess Python support.
    # https://apposed.org/
    - appose

    # Qt is needed for GUI support on macOS.
    # https://github.com/apposed/jaunch/blob/-/doc/MACOS.md#combining-java-awt-and-python-qt
    - PyQt6
    - QtPy

    # Python-based bioimage analysis tools.
    - scikit-image
    - napari[optional]
    - napari-imagej
    - ndv[qt]
